name = "campus-equipment-booking-api"
main = "src/index.ts"
compatibility_date = "2025-09-06"

[vars]
FRONTEND_ORIGIN = "http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "lab_test"
database_id = "c46871d0-ce52-49b0-8046-4e2c2b679574"
migrations_dir = "migrations"